server:
  port: 9005
logging:
  path: F:\project\jvm
  level:
    xyz:
      fanchw: trace
  pattern:
    console: %d{yyyy-MM-dd} [%thread] %-5level %logger{50} - %msg%n
    file: %d{yyyy-MM-dd} === [%thread] === %-5level === %logger{50} ==== %msg%n
